language: go
go:
- "1.10"

before_install:
- go get -u golang.org/x/vgo
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && chmod +x ./cc-test-reporter && ./cc-test-reporter before-build

install:
- dep ensure -v --vendor-only

script:
- vgo build
- vgo test -coverprofile c.out -v ./...

after_script:
- ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: never
    on_failure: change