language: go
go:
- "1.9"

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o $GOPATH/bin/dep
- chmod +x $GOPATH/bin/dep
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

install:
- dep ensure -v --vendor-only

script:
- go vet ./...
- go build ./...
- go test -coverprofile c.out ./...

after_script:
- ./cc-test-reporter after-build --coverage-input-type gocov --exit-code $TRAVIS_TEST_RESULT

notifications:
  email:
    on_success: never
    on_failure: change