language: go
go:
- "1.9"

before_install:
- curl -L -s https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep && chmod +x /go/bin/dep
- dep ensure

script:
- go vet ./...
- go build ./...